### ISSUE TITLE
gen-odoo-patch in 12 branch doesn't generate correct name

### ISSUE THREAD

**Issue by yelizariev** [xoes/odoo-patches#4]
```
$ gen-odoo-patch HEAD odoo
Patch number ####               : 0001
Patch dependencies (csv, ####)  : 
Patch description [a-zA-Z-]     : support-group-by-week-sunday

	0001::support-group-by-week-sunday.patch

You'd better comply with the naming scheme!

regex: '^((?:\d|F)\d\d\d)-(?:(\[(?:(?:|[a-zA-Z_]*?:)(?:\d|F)\d\d\d,)*(?:(?:|[a-zA-Z_]*?:)(?:\d|F)\d\d\d)\])|)::([a-zA-Z-]*?)\.patch$'

```

**Comment by yelizariev** [comment]
Also, what about moving the script to a single special branch?

**Comment by blaggacao** [comment]
> Also, what about moving the script to a single special branch?

Actually whole doc stuff, so to avoid too much cross merging...

Yesterday we where discussing with @ychirino to actually slightly change the semantics to be able to cross reference dependencies across named modules... This is an oversight, thanks.
